// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order.sql

package db

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO ` + "`" + `order` + "`" + ` (
    uuid,
    customer_id,
    customer_payment_method_id,
    cart_id,
    amount,
    address_id,
    discount_id,
    status,
    created_at,
    created_by
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	Uuid                    []byte
	CustomerID              int32
	CustomerPaymentMethodID sql.NullInt32
	CartID                  sql.NullInt32
	Amount                  sql.NullInt32
	AddressID               sql.NullInt32
	DiscountID              sql.NullInt32
	Status                  NullOrderStatus
	CreatedAt               sql.NullTime
	CreatedBy               sql.NullInt32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.Uuid,
		arg.CustomerID,
		arg.CustomerPaymentMethodID,
		arg.CartID,
		arg.Amount,
		arg.AddressID,
		arg.DiscountID,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
	)
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    order_id,
    uuid,
    customer_id,
    customer_payment_method_id,
    cart_id,
    amount,
    address_id,
    discount_id,
    status,
    created_at
FROM ` + "`" + `order` + "`" + `
WHERE order_id = ?
`

type GetOrderByIDRow struct {
	OrderID                 int32
	Uuid                    []byte
	CustomerID              int32
	CustomerPaymentMethodID sql.NullInt32
	CartID                  sql.NullInt32
	Amount                  sql.NullInt32
	AddressID               sql.NullInt32
	DiscountID              sql.NullInt32
	Status                  NullOrderStatus
	CreatedAt               sql.NullTime
}

func (q *Queries) GetOrderByID(ctx context.Context, orderID int32) (GetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, orderID)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.OrderID,
		&i.Uuid,
		&i.CustomerID,
		&i.CustomerPaymentMethodID,
		&i.CartID,
		&i.Amount,
		&i.AddressID,
		&i.DiscountID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT
    order_id,
    uuid,
    customer_id,
    customer_payment_method_id,
    cart_id,
    amount,
    address_id,
    discount_id,
    status,
    created_at
FROM ` + "`" + `order` + "`" + `
ORDER BY created_at DESC
`

type ListOrdersRow struct {
	OrderID                 int32
	Uuid                    []byte
	CustomerID              int32
	CustomerPaymentMethodID sql.NullInt32
	CartID                  sql.NullInt32
	Amount                  sql.NullInt32
	AddressID               sql.NullInt32
	DiscountID              sql.NullInt32
	Status                  NullOrderStatus
	CreatedAt               sql.NullTime
}

func (q *Queries) ListOrders(ctx context.Context) ([]ListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Uuid,
			&i.CustomerID,
			&i.CustomerPaymentMethodID,
			&i.CartID,
			&i.Amount,
			&i.AddressID,
			&i.DiscountID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
